### ISSUE TITLE
Kok ngeleg

### ISSUE THREAD

**Issue by itsmeR1F4I** [Bayu12345677/Instafollowers#1]
Ngeleg bang🗿

**Comment by Bayu12345677** [comment]
emang agak lama

**Comment by Bayu12345677** [comment]
kasi stars lah

**Comment by shoffani20** [comment]
> emang agak lama

Lama nya kisaran berapa menit ya bang

**Comment by Bayu12345677** [comment]
> > emang agak lama
> 
> Lama nya kisaran berapa menit ya bang

30 menitan
